services:
  - type: web
    name: ITkol
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py makemigrations --noinput
      python manage.py migrate --noinput
    startCommand: gunicorn config.wsgi:application
  